name: test

# Run the tests when code is pushed to `main`
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Latte Build
        run: |
          curl -fsSL https://lattejava.org/javaenv/install | bash
          curl -fsSL https://lattejava.org/cli/install | bash
          ~/.local/bin/javaenv install 21
          ~/.local/bin/javaenv install 25
        shell: bash
      - name: Run the build
        run: |
          export PATH=~/.local/bin:$PATH
          latte clean int
        shell: bash
      - name: Archive TestNG reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: build/test-reports
          retention-days: 1
